### ISSUE TITLE
Create modal window to allow player to select category for bonus round

### ISSUE THREAD

**Issue by kchasta2** [dsiver/SnapTrivia#10]

**Comment by dsiver** [comment]
Modal window created and used for bonus question after 3rd correct question. Can probably reuse code for Issue #24

**Comment by dsiver** [comment]
Need to add a button to start challenge.

I will handle logic to determine whether or not both players have at least one different trophy.

The method header will be as follows:

can_challenge?

Edit. Changed method header above

**Comment by B3Chill** [comment]
Completed
