### ISSUE TITLE
Implement In-App purchasing

### ISSUE THREAD

**Issue by kchasta2** [dsiver/SnapTrivia#13]

**Comment by kchasta2** [comment]
Installed the ad-rails gem, which is a helper gem for use with Google Adsense.  Currently, it simply displays a placeholder image on localhost only.  I have emailed the sales team at adsense to see if they have a non-income generating option for educational use or localhost use.

**Comment by kchasta2** [comment]
No response from Google regarding Adsense.  I emailed another company and have had no response either.  Will work on option for adding in-app purchasing in lieu of advertising.

**Comment by kchasta2** [comment]
Sandbox account successfully created.  Buy Now buttons added to Index page.  They redirect to the Paypal sandbox account for completing purchasing.  Working on payment notifications inside the app now.
![screen shot 2015-04-14 at 11 27 33 pm](https://cloud.githubusercontent.com/assets/10480656/7151816/30678200-e2fe-11e4-9344-27c40ae76bf3.png)

**Comment by kchasta2** [comment]
Once you click on Buy Now - the sandbox buyer info is:
SnapBuyer@capstone.edu
LetMeBuy

**Comment by dsiver** [comment]
![screen shot 2015-04-15 at 8 04 22 pm](https://cloud.githubusercontent.com/assets/9600234/7171746/a93b6cd0-e3aa-11e4-9770-a1c4fd0fcaa4.png)

The "Play Random User" and "Search by Player Name" buttons always look like this? Kindof looks like they got sucked into whatever style you're using for the Buy Now stuff

**Comment by kchasta2** [comment]
I put them in a table so I could use unused space to the right of the play random / search player items.  It doesn't look like that on my screen, so thank you for posting that.  I'll revise it and put the purchase buttons in their own table row above the play random / search player and see if it looks better.

**Comment by kchasta2** [comment]
With window scrunched up, it now looks like this:
![image](https://cloud.githubusercontent.com/assets/10480656/7172365/6ab0bb1e-e3b4-11e4-8ed2-8c58690b2468.png)

**Comment by kchasta2** [comment]
The purchasing is part is complete.  Need to add functionality to increment user's coins field in table.

**Comment by kchasta2** [comment]
Functionality to increment coins manually is built in to the administration page for a user.  All fields exist there (apparently this page just iterates through the fields of the table to create the page):

![image](https://cloud.githubusercontent.com/assets/10480656/7215382/1e0d8594-e5a3-11e4-955d-ee20967558be.png)

**Comment by kchasta2** [comment]
Closing this issue - feature does not update automatically, but a purchase can be completed and an admin can update the user's profile with coins after verifying purchase at paypal merchant page.
