### ISSUE TITLE
Notify user when a question they submitted has been approved / rejected

### ISSUE THREAD

**Issue by kchasta2** [dsiver/SnapTrivia#14]

**Comment by dsiver** [comment]
When user creates question, reviewers sent message. User is given flash msg.

**Comment by dsiver** [comment]
Right now, when Question is approved, a message goes out to Admins because there is no way to link a user to their question.

**Comment by B3Chill** [comment]
I'll add a field for submitted by

**Comment by B3Chill** [comment]
to the question sorry

**Comment by dsiver** [comment]
Should it be another table with foreign keys? Call it UserQuestions and
have question_id & user_id columns?

Thanks,

David Siver

**Comment by dsiver** [comment]
This is currently working. I had to add a reference to the user ID in questions table.

I cannot resolve this issue until the Messages Issue #17 is resolved first.
