### ISSUE TITLE
Player Search

### ISSUE THREAD

**Issue by kchasta2** [dsiver/SnapTrivia#16]
### Could pull this off any of the following ways:
- Existing search box that looks for a player and displays a notice if none found.  
- Drop down list of players
- Create user controller and index page. Send search param to index. Sort all users by search. Provide link_to back to game controller.  
### Starting the Game
- Use a button just like the one next to the list of player names below the search box.

**Comment by B3Chill** [comment]
Half done, built gui now have to tie it to backend

**Comment by B3Chill** [comment]
Player search completed.  When searched user is directed to another page where they can view the player profile and start a game against the searched player
