### ISSUE TITLE
Fix Style of Trophies on Game Page

### ISSUE THREAD

**Issue by B3Chill** [dsiver/SnapTrivia#25]

**Comment by dsiver** [comment]
Are these the trophies that get added during gameplay?

**Comment by B3Chill** [comment]
Yes

**Comment by dsiver** [comment]
Update:
Appearing on page. However, they show up horizontally. Sometimes, not at all. Need to see what is happening with font awesome icons

**Comment by dsiver** [comment]
Update:
I think I have this implemented correctly. I am about to start testing it.

**Comment by B3Chill** [comment]
moved the trophies underneath the player name, still needs better formatting by using icon placeholders

**Comment by dsiver** [comment]
made all same size in commit e3fd91e2574ca07a606b7b04ac19ed57816faa8b
