### ISSUE TITLE
Add Option to Delete past games game/index

### ISSUE THREAD

**Issue by B3Chill** [dsiver/SnapTrivia#38]

**Comment by dsiver** [comment]
Could create partial form for game and show. Game would include spinner, Show would not.

User clicks on button shown in finished game at index. Renders Show and they cannot play spinner.

If user deletes game, I presume it will no longer show in their opponent's list either.

**Comment by dsiver** [comment]
Not in Must Haves. Minor. This could also break the functionality of Issue #75
