### ISSUE TITLE
Indicate Number of Correct Questions on Game Page

### ISSUE THREAD

**Issue by B3Chill** [dsiver/SnapTrivia#40]

**Comment by dsiver** [comment]
Backend implemented, this updates GUI for user.

**Comment by dsiver** [comment]
No longer working. Necessary changes to the game affected this.

**Comment by dsiver** [comment]
Added minor tag because this is not on Must Haves spec from Yoder. Could simply implement this with putting answers_correct in HTML

**Comment by dsiver** [comment]
Can be a simple print out to the game page with a number or using font awesome stuff
