### ISSUE TITLE
Currently logged in player always appears on left of window

### ISSUE THREAD

**Issue by kchasta2** [dsiver/SnapTrivia#69]
Related to: #40 
In an active game, the currently active player always appears on the left side of the window. This is causing the following bugs (see screen capture):
1) Stats belonging to the player who started the game appear to belong to the other player when that player is logged in

2) The 2nd player (the one who did not start the game) appear to be playing themselves when they are logged in and choose to continue the active game
- Possible solution: Modify code so the player who starts the game is always player 1 (on left side of window) and other player is always player 2 (right side of window)

![image](https://cloud.githubusercontent.com/assets/10480656/7036404/89816618-dd62-11e4-8fc3-7d1b66af153f.png)

**Comment by B3Chill** [comment]
It's just for testing. All those stats will go away soon.

**Comment by kchasta2** [comment]
I know.. but it's not about the stats.  If we line up questions correct icons and trophies under the player on the left - they will appear to belong to the other player if they are the one logged in - as shown in the screen capture on the right.

**Comment by B3Chill** [comment]
What you see is data that I put up. When you put in the icons we have to
tie them to the logic and the user/player2.  What you see is not tied into
a profile.
Bill

**Comment by kchasta2** [comment]
The yellow checkmark icon is what I created to signify questions correct.  It will increment up to 3 and start over.  Can you show me tomorrow how you're tying information into player1 vs player2?

**Comment by dsiver** [comment]
I did not realize there was a "question" label when I recommended Kristi create this issue. Question seems more appropriate.
