### ISSUE TITLE
Implement Challenge in Game Controller

### ISSUE THREAD

**Issue by kchasta2** [dsiver/SnapTrivia#7]
Tied to Issues #77 & #78

**Comment by dsiver** [comment]
As it stands now, all my tests for can_challenge are passing in the Game model.
The tests for trophies include:
- for none
- each has the same
- each has 1, both different
- each has multiple, all same
- each has multiple, all different
- each has multiple, some different
- challenger has nothing to wager
- challenger has nothing to win

**Comment by dsiver** [comment]
Added test for @game.challenge == "yes" to call method to start challenge.

Method to start it is private in game controller.

**Comment by dsiver** [comment]
So far, I have tested game.get_wagerable_trophies & game.get_winnable_trophies for the following criteria and all tests are passing:
- none in common
- one in common
- some in common
- all in common

**Comment by dsiver** [comment]
Now that I have built and tested the Challenge model, I need to handle swapping trophies based upon the winner in game.

**Comment by dsiver** [comment]
# Note to self

### Game model:
- [x] create take_trophy(subject, user_id) 
  - [x] tested?
- [x] finish writing play_challenge
  - [x] tested?
- [x] write apply_challenge_results
  - [x] tested?

### Challenge model:
- [x] finish set_winner 
  - [x] tested?

**Comment by dsiver** [comment]
Working in game_controller to apply challenge

**Comment by dsiver** [comment]
As challenger, using Chrome, 2nd question (Entertainment) is intermittently skipped. Challenge counter and challenger correct is incremented by 1.
