### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by kchasta2** [dsiver/SnapTrivia#75]
## MUST HAVE PER YODER SPEC
- [x] Check Calculations on Pages to Ensure Accurate Measurements
- [x] 5 Achievements  
- [x] Individual Stats  
  - [x] Category Performance  
  - [x] Record v. Specific Opponent  
- [x] Site Stats (All Below Include Category Percentage and Total Number Correct)  
  - [x] Weekly  
  - [x] Monthly  
  - [x] Overall  
- [x] Generate Seed Data  
  - [x] Finished Games (create a few months worth of history)  
  - [x] GameStat for each finished game  
  - [x] Apply game results to player1 and player2  
#### Note

Related to Issue #74. I am closing that one to make things easier for us to keep track of things.

**Comment by kchasta2** [comment]
Site stats page is in for overall stats - needs styling.

**Comment by kchasta2** [comment]
Can't figure out how to pull weekly / monthly site stats - any ideas appreciated

**Comment by B3Chill** [comment]
completed
