### ISSUE TITLE
Power Ups

### ISSUE THREAD

**Issue by dsiver** [dsiver/SnapTrivia#76]
### Gameplay
- What happens to the power up button if the user has no more remaining?  
- [x] put in modal where question is asked  
- [x] deduct cost from User's coins  
### Implementation

Might be wrong. Could just tie directly into coins.  Refactor "has" methods to see if their coins are divisible by cost of power up.  
### User
- [x] tie to rewarded coins based upon statistics  
- [x] test

**Comment by B3Chill** [comment]
completed and works with all three power up buttons.
