### ISSUE TITLE
Challenge View

### ISSUE THREAD

**Issue by dsiver** [dsiver/SnapTrivia#77]
If both players have at least one different trophy each, the player can choose to challenge their opponent.

Displayed if player clicks "Challenge" button when arriving at a bonus question's modal to select the next question's category.

Player chooses which trophy to wager from a list of ones they currently possess.

Player chooses which trophy to win from a list of the opponent's trophies, minus any they both possess.

Challenge starts after clicking a submit button, provided they chose a trophy to wager and win.

**Comment by B3Chill** [comment]
working on a two column button select modal

**Comment by dsiver** [comment]
Submit appears to stall game.

**Comment by B3Chill** [comment]
Completed launches as a page
