### ISSUE TITLE
Challenge Class

### ISSUE THREAD

**Issue by dsiver** [dsiver/SnapTrivia#78]
# Summary
## Creation

If created calling only Challenge.new, id attributes will default to 0, except for question ids (generated randomly on its own). Can be created via Challenge.new while passing in params for all attributes, but generation of question ids should be left to the object itself.
#### generate_question_ids

Gets a random question by each category and sets all of its id attributes accordingly.  
#### apply_question_result(user_id, result, bonus_flag, question_number)
- params  
  - user_id: the id of the user answering the question. Typically the current user  
  - result: needs to be a constant from the Question object. Question::INCORRECT or Question::CORRECT  
  - bonus_flag: needs to be a constant from the Game object. Game::BONUS_TRUE or Game::BONUS_FALSE  
  - question_number: should be an int value 1 - 7  
- return value  
  - Challenge::RESULT_OPPONENT_TURN after the challenger answers the 6th question.
  - Challenge::RESULT_TIE if there is a tie after each player gets the first 6 questions  
  - Challenge::RESULT_WINNER if there is a winner. This does not return the winner's id.

**Comment by dsiver** [comment]
Working on method in challenge class to determine winner.

**Comment by kchasta2** [comment]
Is this also part of #10? Or can we close that issue?  Modal window for bonus round appears to be fully operational on Heroku.

**Comment by dsiver** [comment]
If you read the comments for #10
https://github.com/dsiver/SnapTrivia/issues/10, I mentioned it needed to
have a button to start the challenge based upon whether or not a challenge
can happen.

I know Bill had it showing up. I created the method necessary to toggle its
appearance for the game model.

As of right now, that feature is not implemented in the game, which is why
I left it open.

**Comment by dsiver** [comment]
Currently working on:
- Trophy swap after challenge
- Tie breaker

**Comment by dsiver** [comment]
Challenge implemented in Game

**Comment by dsiver** [comment]
# Tests

### apply_question_results

#### challenger_correct
- 1 after 1st question correct  
- 0 after 1st question incorrect  

#### opponent_correct
- 0 after challenger turn  
- 1 after 1st question correct  
- 7 after 6 correct in a row followed by bonus question  

#### return value
- Challenge::RESULT_OPPONENT_TURN  
  - not returned after bonus question correct  
  - returned after challenger's 6th question  
- Challenge::RESULT_TIE  
  - not returned after opponent gets bonus question correct  
  - not returned after opponent answers 6th question incorrectly  
  - returned if tie  
- Challenge::RESULT_WINNER  
  - returned after opponent gets bonus question correct  
  - returned after opponent gets 6th question incorrect  

#### raises error when
- question number does not match counter  
- challenger gets question number > 6 while bonus is false  
- challenger gets a question while bonus is true  
- opponent gets question number > 6 while bonus is false  
- opponent gets question number != 7 while bonus is true  

#### nothing is raised when
- opponent gets 7th question while bonus is true  

#### winner_id
- == opponent_id  
  - after opponent answers bonus question correctly  
  - 0v1, 5v6  
- == challenger_id  
  - after opponent answers bonus question incorrectly  
  - 1v0, 6v5  

#### get_total_correct
- using challenger_id  
  - checked against actual score  
  - not opponent's  
- using opponent_id  
  - actual score  
  - not challenger's  

#### counter
- == 0 after initialization
- using apply_question_results  
  - incremented by 1 from 1 - 6 times with either Question::CORRECT or Question::INCORRECT for challenger and opponent with Game::BONUS_FALSE  
  - == 7 after opponent gets 6 questions followed by Game::BONUS_TRUE

**Comment by dsiver** [comment]
Implemented and tested
