### ISSUE TITLE
Allow user to request to be a Reviewer

### ISSUE THREAD

**Issue by kchasta2** [dsiver/SnapTrivia#8]

**Comment by dsiver** [comment]
Having trouble with the boolean value request_reviewer. Thinking of abandoning the request checkbox in user profile and having user send the administrator a request with a messaging system.

**Comment by dsiver** [comment]
Having trouble using the request checkbox in edit profile page to msg the administrator. Thinking of just having the user send a message requesting.

**Comment by dsiver** [comment]
Implemented via messaging system. User can send msg to Admin and request to be reviewer. Admin has hyperlink directly to that user's dashboard profile in message. Pages need to be beautified.

**Comment by dsiver** [comment]
Cannot be resolved until Messages Issue #17 is resolved first.
