### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by dsiver** [dsiver/SnapTrivia#84]
#### Could Be Any of the Following:
- [x] Answer Correct  
- [x] Answer Incorrect  
- [ ] Player Wins  
- [ ] Player Loses  
- [ ] Spinner Wheel  
- [x] Timer for Question Page

**Comment by dsiver** [comment]
Okay, I have the setting created for users if they want to hear sounds. You can access it from current_user.play_sounds? I don't know how you implemented playing them, but you can look at how I toggled the profile picture on and off in application.html.erb and use the same technique.

**Comment by kchasta2** [comment]
3 of the 6 implemented - game has sound. Closing issue.
