### ISSUE TITLE
Profile Information

### ISSUE THREAD

**Issue by dsiver** [dsiver/SnapTrivia#85]
## MUST HAVE PER YODER SPEC
- [x] Picture (Currently shows URL path in user's profile. Need to verify this works.  
- [x] Add location to database and form fields for creating account.  
#### Note

Could implement "Profile Picture Visibility" from Issue #83 here.

**Comment by kchasta2** [comment]
Can you check functionality for changing profile?  It always says "current password cannot be blank" even if it's entered.  (Note - this is on Heroku)

![image](https://cloud.githubusercontent.com/assets/10480656/7192739/44145a1c-e466-11e4-9c18-3edf01181d82.png)

**Comment by dsiver** [comment]
Was it a social media login?

Thanks,

David Siver

**Comment by kchasta2** [comment]
No - I logged in with my regular email gakristi@gmail.com and set the pw as
password

**Comment by kchasta2** [comment]
Picture bug fixed

![image](https://cloud.githubusercontent.com/assets/10480656/7241438/efe8b6da-e786-11e4-972b-ff23c4e49cc3.png)
