### ISSUE TITLE
Update Game Index After Resigning Game

### ISSUE THREAD

**Issue by kchasta2** [dsiver/SnapTrivia#9]
## MUST HAVE PER YODER SPEC

All this would consist of is placing a button in two places and use it to call the game's instance method 'end_game'
- in game.html.erb
- in each game of index.html.erb (works, but page does not refresh the section

**Comment by dsiver** [comment]
All this would consist of is placing a button in two places and use it to call the instance method 'end_game'
* in game.html.erb
* in each game of index.html.erb

**Comment by dsiver** [comment]
I pushed work for this to the repo moments ago, but I forgot to put a space before the # sign. dc6064274b3996e94ea8ae7be9612822fe06d869 is the commit.

I need to refresh the page after this happens.
